on: push
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm  --version
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test